"""
Sync scenario/quest data from RingsDB API → scenarios/ and cycles/ vault directories.

Usage:
    python scripts/sync_scenarios.py
    python scripts/sync_scenarios.py --force
"""

import json
import argparse
from pathlib import Path

import requests
from slugify import slugify

VAULT_ROOT = Path(__file__).parent.parent
SCENARIOS_DIR = VAULT_ROOT / "scenarios"
CYCLES_DIR = VAULT_ROOT / "cycles"
CACHE_DIR = Path(__file__).parent / "cache"

RINGSDB_PACKS_URL = "https://ringsdb.com/api/public/packs/"

CACHE_DIR.mkdir(exist_ok=True)

GENERATED_COMMENT = "<!-- generated by scripts/sync_scenarios.py — do not edit manually -->\n"

# RingsDB has no /cycles/ endpoint — cycle_position on packs encodes the grouping.
# cycle_position values: standalone packs have unique positions; AP cycles share a position.
# Deluxe boxes that open cycles are identified by having position=1 within their group.
CYCLE_NAMES = {
    1:  "Core Set",
    2:  "Revised Core Set",
    10: "Shadows of Mirkwood",
    11: "Khazad-dûm",
    12: "Dwarrowdelf",
    13: "Heirs of Númenor",
    14: "Against the Shadow",
    15: "The Voice of Isengard",
    16: "The Ring-maker",
    17: "The Lost Realm",
    18: "Angmar Awakened",
    19: "The Grey Havens",
    20: "Dream-chaser",
    21: "The Sands of Harad",
    22: "Haradrim",
    23: "The Wilds of Rhûn",
    24: "Ered Mithrin",
    25: "A Shadow in the East",
    26: "Vengeance of Mordor",
    27: "The Hobbit",
    28: "The Lord of the Rings Saga",
    29: "GenCon/Fellowship",
    30: "Nightmare Decks",
    31: "Special",
    32: "Standalone",
    33: "Two-Player Limited Edition Starter",
    40: "Starter",
    41: "Revised",
    50: "The Dark of Mirkwood",
    60: "Print on Demand",
    61: "Deluxe Expansion",
    70: "League",
}


def fetch_packs(force: bool = False) -> list[dict]:
    cache_file = CACHE_DIR / "packs.json"
    if not force and cache_file.exists():
        print(f"Using cached pack data from {cache_file}")
        return json.loads(cache_file.read_text())
    print(f"Fetching {RINGSDB_PACKS_URL} ...")
    resp = requests.get(RINGSDB_PACKS_URL, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    cache_file.write_text(json.dumps(data, indent=2))
    return data


def cycle_name_for_pack(pack: dict) -> str:
    pos = pack.get("cycle_position", 0)
    return CYCLE_NAMES.get(pos, f"Cycle {pos}")


def cycle_to_markdown(cycle_name: str, packs: list[dict]) -> str:
    lines = [GENERATED_COMMENT, "---"]
    lines.append(f'title: "{cycle_name}"')
    lines.append(f'cycle_position: {packs[0].get("cycle_position", 0)}')
    lines.append("tags: [cycle]")
    lines.append("---")
    lines.append(f"\n# {cycle_name}\n")
    lines.append("## Packs\n")
    for p in sorted(packs, key=lambda x: x.get("position", 0)):
        lines.append(f"- [[{p['name']}]]")
    return "\n".join(lines)


def pack_to_scenario_markdown(pack: dict, cycle_name: str) -> str:
    name = pack.get("name", "")
    lines = [GENERATED_COMMENT, "---"]
    lines.append(f'title: "{name}"')
    lines.append(f'cycle: "{cycle_name}"')
    lines.append(f'pack_code: "{pack.get("code", "")}"')
    lines.append(f'position: {pack.get("position", 0)}')
    lines.append(f'available: "{pack.get("available", "")}"')
    lines.append("difficulty: \"\"  # Easy | Medium | Hard | Brutal — fill in manually")
    lines.append("solo_friendly: null  # true | false — fill in manually")
    lines.append(f"tags: [scenario, {slugify(cycle_name)}]")
    lines.append("---")
    lines.append(f"\n# {name}\n")
    lines.append(f"**Cycle:** [[{cycle_name}]]\n")
    lines.append("## Notes\n\n<!-- Add scenario notes, tips, and difficulty assessment here -->\n")
    return "\n".join(lines)


def sync_scenarios(force: bool = False):
    packs = fetch_packs(force=force)
    print(f"Processing {len(packs)} packs ...")

    # Group packs by cycle_position to generate cycle index files
    from collections import defaultdict
    by_cycle = defaultdict(list)
    for pack in packs:
        by_cycle[pack.get("cycle_position", 0)].append(pack)

    written = updated = skipped = 0

    for cycle_pos, cycle_packs in by_cycle.items():
        name = CYCLE_NAMES.get(cycle_pos, f"Cycle {cycle_pos}")
        path = CYCLES_DIR / (slugify(name) + ".md")
        content = cycle_to_markdown(name, cycle_packs)
        if path.exists() and path.read_text() == content:
            skipped += 1
        else:
            path.write_text(content)
            updated += 1

    for pack in packs:
        cycle_name = cycle_name_for_pack(pack)
        path = SCENARIOS_DIR / (slugify(pack["name"]) + ".md")
        content = pack_to_scenario_markdown(pack, cycle_name)
        if path.exists() and path.read_text() == content:
            skipped += 1
        else:
            path.write_text(content)
            updated += 1

    print(f"Done. Updated: {updated}  Unchanged: {skipped}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Sync LOTR LCG scenarios from RingsDB")
    parser.add_argument("--force", action="store_true", help="Ignore cache and re-fetch from API")
    args = parser.parse_args()
    sync_scenarios(force=args.force)
