"""
Sync all player cards from RingsDB API → cards/ vault directory.

Usage:
    python scripts/sync_cards.py           # sync all cards
    python scripts/sync_cards.py --force   # ignore cache, re-fetch from API
"""

import json
import re
import argparse
from pathlib import Path
from typing import Optional

import requests
from slugify import slugify

VAULT_ROOT = Path(__file__).parent.parent
CARDS_DIR = VAULT_ROOT / "cards"
IMAGES_DIR = CARDS_DIR / "images"
CACHE_DIR = Path(__file__).parent / "cache"
RINGSDB_CARDS_URL = "https://ringsdb.com/api/public/cards/"
RINGSDB_IMAGE_BASE = "https://ringsdb.com"

CACHE_DIR.mkdir(exist_ok=True)
IMAGES_DIR.mkdir(exist_ok=True)

# Maps RingsDB type_code → subdirectory
TYPE_DIRS = {
    "hero": "heroes",
    "ally": "allies",
    "attachment": "attachments",
    "event": "events",
    "player-side-quest": "player-side-quests",
    "contract": "contracts",
}

GENERATED_COMMENT = "<!-- generated by scripts/sync_cards.py — do not edit manually -->\n"


def fetch_card_image(card: dict) -> Optional[str]:
    """Download card image to IMAGES_DIR if not already present. Returns filename or None."""
    imagesrc = card.get("imagesrc")
    if not imagesrc:
        return None
    code = card.get("code", "")
    filename = f"{code}.png"
    dest = IMAGES_DIR / filename
    if not dest.exists():
        try:
            resp = requests.get(RINGSDB_IMAGE_BASE + imagesrc, timeout=15)
            resp.raise_for_status()
            dest.write_bytes(resp.content)
        except requests.RequestException:
            return None
    return filename


def fetch_cards(force: bool = False) -> list[dict]:
    cache_file = CACHE_DIR / "cards.json"
    if not force and cache_file.exists():
        print(f"Using cached card data from {cache_file}")
        return json.loads(cache_file.read_text())

    print(f"Fetching cards from {RINGSDB_CARDS_URL} ...")
    resp = requests.get(RINGSDB_CARDS_URL, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    cache_file.write_text(json.dumps(data, indent=2))
    print(f"Cached {len(data)} cards to {cache_file}")
    return data


# Callout type per sphere — maps to Obsidian's built-in rendered styles
SPHERE_CALLOUT = {
    "leadership": "tip",      # gold/green
    "tactics":    "danger",   # red
    "spirit":     "info",     # blue
    "lore":       "note",     # green
    "neutral":    "abstract", # grey
    "baggins":    "example",
    "fellowship": "success",
}

# Short emoji label per sphere for the stat-block header line
SPHERE_ICON = {
    "leadership": "👑",
    "tactics":    "⚔️",
    "spirit":     "💧",
    "lore":       "📖",
    "neutral":    "⚪",
    "baggins":    "🍃",
    "fellowship": "💍",
}


def sphere_tag(sphere_code: str) -> str:
    return sphere_code.lower() if sphere_code else "neutral"


ICON_MAP = {
    "[willpower]":  "WP",
    "[attack]":     "ATK",
    "[defense]":    "DEF",
    "[Defense]":    "DEF",
    "[threat]":     "Threat",
    "[leadership]": "(Leadership)",
    "[tactics]":    "(Tactics)",
    "[spirit]":     "(Spirit)",
    "[lore]":       "(Lore)",
    "[baggins]":    "(Baggins)",
    "[fellowship]": "(Fellowship)",
    "[pp]":         "progress",
}


def clean_html(text: str) -> str:
    """Convert RingsDB HTML tags and icon placeholders to Markdown."""
    text = text.replace("<b>", "**").replace("</b>", "**")
    text = text.replace("<i>", "_").replace("</i>", "_")
    text = text.replace("<br />", "\n").replace("<br/>", "\n").replace("<br>", "\n")
    # <cite> → em-dash attribution on its own line (strip leading whitespace/newlines before tag)
    text = re.sub(r"\s*<cite>(.*?)</cite>", r"\n— \1", text, flags=re.DOTALL)
    # Strip any remaining HTML tags
    text = re.sub(r"<[^>]+>", "", text)
    # Replace icon placeholders
    for placeholder, label in ICON_MAP.items():
        text = text.replace(placeholder, label)
    return text.strip()


def parse_traits(raw: str) -> list[str]:
    return [t.strip().rstrip(".") for t in raw.split(".") if t.strip()] if raw else []


def parse_flavor(raw: str) -> tuple[str, str]:
    """Split flavor text into (quote, attribution). Returns ('', '') if empty."""
    if not raw:
        return "", ""
    cleaned = clean_html(raw)
    # Attribution follows an em-dash on the last line
    lines = cleaned.strip().splitlines()
    if lines and lines[-1].startswith("—"):
        return "\n".join(lines[:-1]).strip(), lines[-1].strip()
    return cleaned, ""


def build_front_matter(card: dict) -> str:
    c = card
    type_code = c.get("type_code", "")
    sphere_code = c.get("sphere_code", "neutral")
    lines = ["---"]
    lines.append(f'title: "{c.get("name", "")}"')
    lines.append(f'ringsdb_id: "{c.get("code", "")}"')
    lines.append(f'type: {c.get("type_name", "")}')
    lines.append(f'sphere: {c.get("sphere_name", "Neutral")}')

    if type_code == "hero":
        lines.append(f'threat: {c.get("threat", c.get("cost", 0))}')
        for stat, key in [("willpower", "willpower"), ("attack", "attack"), ("defense", "defense"), ("health", "hit_points")]:
            val = c.get(stat)
            if val is not None:
                lines.append(f"{key}: {val}")
    elif type_code in ("ally",):
        cost = c.get("cost")
        lines.append(f"cost: {cost if cost is not None else 'X'}")
        for stat, key in [("willpower", "willpower"), ("attack", "attack"), ("defense", "defense"), ("health", "hit_points")]:
            val = c.get(stat)
            if val is not None:
                lines.append(f"{key}: {val}")
    elif type_code == "player-side-quest":
        cost = c.get("cost", 0)
        lines.append(f"cost: {cost}")
        lines.append(f'quest_points: {c.get("quest", 0)}')
        if c.get("victory") is not None:
            lines.append(f'victory: {c["victory"]}')
    else:
        cost = c.get("cost")
        if cost is not None:
            lines.append(f"cost: {cost}")

    traits = parse_traits(c.get("traits", ""))
    if traits:
        lines.append(f"traits: [{', '.join(traits)}]")

    lines.append(f'unique: {str(bool(c.get("is_unique"))).lower()}')
    lines.append(f'pack: "{c.get("pack_name", "")}"')
    lines.append(f'pack_code: "{c.get("pack_code", "")}"')
    lines.append(f'position: {c.get("position", 0)}')
    lines.append(f'deck_limit: {c.get("deck_limit", 3)}')

    type_tag = type_code.replace("-", "")
    lines.append(f"tags: [card, {type_tag}, {sphere_tag(sphere_code)}]")
    lines.append("---")
    return "\n".join(lines)


def stat_block_hero(card: dict, callout: str) -> str:
    threat = card.get("threat", card.get("cost", "?"))
    wp = card.get("willpower", 0)
    atk = card.get("attack", 0)
    dfn = card.get("defense", 0)
    hp = card.get("health", 0)
    sphere = card.get("sphere_name", "")
    icon = SPHERE_ICON.get(card.get("sphere_code", "neutral"), "")
    return (
        f"> [!{callout}] {icon} Hero · Threat: **{threat}** · {sphere}\n"
        f"> **WP** {wp}  ·  **ATK** {atk}  ·  **DEF** {dfn}  ·  **HP** {hp}"
    )


def stat_block_ally(card: dict, callout: str) -> str:
    cost = card.get("cost", "?")
    wp = card.get("willpower", 0)
    atk = card.get("attack", 0)
    dfn = card.get("defense", 0)
    hp = card.get("health", 0)
    sphere = card.get("sphere_name", "")
    icon = SPHERE_ICON.get(card.get("sphere_code", "neutral"), "")
    return (
        f"> [!{callout}] {icon} Ally · Cost: **{cost}** · {sphere}\n"
        f"> **WP** {wp}  ·  **ATK** {atk}  ·  **DEF** {dfn}  ·  **HP** {hp}"
    )


def stat_block_simple(card: dict, callout: str) -> str:
    type_name = card.get("type_name", "Card")
    cost = card.get("cost")
    sphere = card.get("sphere_name", "")
    icon = SPHERE_ICON.get(card.get("sphere_code", "neutral"), "")
    cost_str = f" · Cost: **{cost}**" if cost is not None else ""
    return f"> [!{callout}] {icon} {type_name}{cost_str} · {sphere}"


def stat_block_side_quest(card: dict, callout: str) -> str:
    cost = card.get("cost", 0)
    qp = card.get("quest", 0)
    victory = card.get("victory")
    sphere = card.get("sphere_name", "Neutral")
    icon = SPHERE_ICON.get(card.get("sphere_code", "neutral"), "")
    victory_str = f"  ·  **Victory** {victory}" if victory is not None else ""
    return (
        f"> [!{callout}] {icon} Player Side Quest · Cost: **{cost}** · {sphere}\n"
        f"> **Quest Points:** {qp}{victory_str}"
    )


def build_card_body(card: dict, image_filename: Optional[str] = None) -> str:
    name = card.get("name", "")
    unique_marker = " ◆" if card.get("is_unique") else ""
    type_code = card.get("type_code", "")
    sphere_code = card.get("sphere_code", "neutral")
    callout = SPHERE_CALLOUT.get(sphere_code, "abstract")

    parts = [f"# {name}{unique_marker}\n"]

    # Stat block callout
    if type_code == "hero":
        parts.append(stat_block_hero(card, callout))
    elif type_code == "ally":
        parts.append(stat_block_ally(card, callout))
    elif type_code == "player-side-quest":
        parts.append(stat_block_side_quest(card, callout))
    else:
        parts.append(stat_block_simple(card, callout))

    # Card image
    if image_filename:
        parts.append(f"\n![[{image_filename}]]")

    # Traits
    traits = parse_traits(card.get("traits", ""))
    if traits:
        parts.append(f"\n*{'. '.join(traits)}.*")

    # Card text
    raw_text = card.get("text", "").strip()
    if raw_text:
        parts.append("\n---\n")
        parts.append(clean_html(raw_text))

    # Flavor text
    quote, attribution = parse_flavor(card.get("flavor", ""))
    if quote:
        parts.append("\n---\n")
        for line in quote.splitlines():
            parts.append(f"> *{line}*")
        if attribution:
            parts.append(f"> {attribution}")

    # Pack footer
    pack_name = card.get("pack_name", "")
    position = card.get("position", "")
    deck_limit = card.get("deck_limit", 3)
    type_code = card.get("type_code", "")
    # Heroes always have deck_limit 1 — not worth repeating; show for other unusual limits
    show_limit = deck_limit != 3 and type_code != "hero"
    limit_str = f" · Limit {deck_limit} per deck" if show_limit else ""
    if pack_name:
        parts.append(f"\n**Pack:** [[{pack_name}]] #{position}{limit_str}")

    return "\n".join(parts)


NOTES_MARKER = "\n\n---\n\n## Notes\n"
NOTES_PLACEHOLDER = "\n\n---\n\n## Notes\n\n<!-- Tips, combos, and strategy notes -->\n"


def extract_existing_notes(path: Path) -> str:
    """Return the ## Notes section and everything after it from an existing file."""
    if not path.exists():
        return ""
    content = path.read_text()
    idx = content.find(NOTES_MARKER)
    return content[idx:] if idx != -1 else ""


def card_to_markdown(card: dict, existing_path=None, image_filename: Optional[str] = None) -> str:
    generated = GENERATED_COMMENT + build_front_matter(card) + "\n\n" + build_card_body(card, image_filename)
    notes = extract_existing_notes(existing_path) if existing_path else ""
    return generated + (notes if notes else NOTES_PLACEHOLDER)


SAFE_NAME_RE = re.compile(r'[<>:"/\\|?*]')

def safe_filename(name: str) -> str:
    return SAFE_NAME_RE.sub("", name).strip()

def output_path(card: dict, hero_names_with_duplicates: set) -> Path:
    type_code = card.get("type_code", "ally")
    subdir = TYPE_DIRS.get(type_code, "allies")
    name = card.get("name", "unknown")
    # Heroes with multiple sphere versions — disambiguate as "Name (Sphere)"
    if type_code == "hero" and name in hero_names_with_duplicates:
        sphere = card.get("sphere_name", "Neutral")
        filename = safe_filename(f"{name} ({sphere})") + ".md"
    else:
        filename = safe_filename(name) + ".md"
    return CARDS_DIR / subdir / filename


def find_duplicate_hero_names(cards: list[dict]) -> set:
    from collections import Counter
    counts = Counter(c["name"] for c in cards if c.get("type_code") == "hero")
    return {name for name, n in counts.items() if n > 1}


def sync_cards(force: bool = False):
    cards = fetch_cards(force=force)
    player_cards = [c for c in cards if c.get("type_code") in TYPE_DIRS]
    duplicate_heroes = find_duplicate_hero_names(player_cards)
    print(f"Processing {len(player_cards)} player cards ({len(duplicate_heroes)} heroes with multiple versions) ...")

    written = updated = skipped = img_downloaded = img_failed = 0
    for i, card in enumerate(player_cards, 1):
        if i % 100 == 0:
            print(f"  {i}/{len(player_cards)} cards processed ...")

        image_filename = fetch_card_image(card)
        if image_filename:
            dest = IMAGES_DIR / image_filename
            if dest.stat().st_size > 0:
                img_downloaded += 1
        elif card.get("imagesrc"):
            img_failed += 1

        path = output_path(card, duplicate_heroes)
        content = card_to_markdown(card, existing_path=path, image_filename=image_filename)
        if path.exists() and path.read_text() == content:
            skipped += 1
            continue
        path.write_text(content)
        if path.exists():
            updated += 1
        else:
            written += 1

    print(f"Done. Written: {written}  Updated: {updated}  Unchanged: {skipped}")
    print(f"Images: {img_downloaded} available" + (f", {img_failed} failed" if img_failed else ""))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Sync LOTR LCG cards from RingsDB")
    parser.add_argument("--force", action="store_true", help="Ignore cache and re-fetch from API")
    args = parser.parse_args()
    sync_cards(force=args.force)
